# Gateway configuration example
esphome:
  name: nrf24_gateway
  libraries:
    - "RF24@1.4.5"
  # friendly_name: test

esp8266:
  board: esp12e

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:

# Enable OTA updates
ota:

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal)
  ap:
    ssid: "Nrf24 Gateway"
    password: "12345678"

# Enable Web server
web_server:
  port: 80

# Configure SPI bus
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

# Configure NRF24L01
nrf24l01:
  ce_pin: GPIO4
  csn_pin: GPIO5
  mode: gateway
  hubs:
    - pipe: 0
      address: "HUB01"
    - pipe: 1
      address: "HUB02" 